In [1]:
import pandas as pd 
import numpy as np

In [2]:
path = 'nqm_monitor.csv'

In [4]:
df = pd.read_csv(path)

In [5]:
df

,Textbox38,Textbox51,Textbox55,Textbox180,Textbox175,Textbox6,Textbox115,Textbox129,Textbox13,Textbox15,...,Textbox210,Textbox211,Textbox16,Textbox28,Textbox35,Textbox83,Textbox43,Textbox49,Textbox58,Textbox77
0,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
1,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
2,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
3,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
4,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1069,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
1070,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
1071,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
1072,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502
1073,Grading,Completed Works,Ongoing Works,Sr.No.,Monitor,Year,Month,State,District,S,...,237,"2,915",696,70,212,978,343,92,67,502

In [6]:
print(df)

     Textbox38        Textbox51      Textbox55 Textbox180 Textbox175 Textbox6  \
0      Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
1      Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
2      Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
3      Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
4      Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
...        ...              ...            ...        ...        ...      ...
1069   Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
1070   Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
1071   Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
1072   Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year
1073   Grading  Completed Works  Ongoing Works     Sr.No.    Monitor     Year

     Textbox115 Textbox129 Textbox13 Textbox15  ... Textbox210 Textbox211  \
0         Month      State  District         S  ...        237      2,915
1         Month      State  District         S  ...        237      2,915
2         Month      State  District         S  ...        237      2,915
3         Month      State  District         S  ...        237      2,915
4         Month      State  District         S  ...        237      2,915
...         ...        ...       ...       ...  ...        ...        ...
1069      Month      State  District         S  ...        237      2,915
1070      Month      State  District         S  ...        237      2,915
1071      Month      State  District         S  ...        237      2,915
1072      Month      State  District         S  ...        237      2,915
1073      Month      State  District         S  ...        237      2,915

     Textbox16 Textbox28 Textbox35 Textbox83 Textbox43 Textbox49 Textbox58  \
0          696        70       212       978       343        92        67
1          696        70       212       978       343        92        67
2          696        70       212       978       343        92        67
3          696        70       212       978       343        92        67
4          696        70       212       978       343        92        67
...        ...       ...       ...       ...       ...       ...       ...
1069       696        70       212       978       343        92        67
1070       696        70       212       978       343        92        67
1071       696        70       212       978       343        92        67
1072       696        70       212       978       343        92        67
1073       696        70       212       978       343        92        67

     Textbox77
0          502
1          502
2          502
3          502
4          502
...        ...
1069       502
1070       502
1071       502
1072       502
1073       502

[1074 rows x 81 columns]