In [11]:
import pandas as pd 
import numpy as np

In [12]:
path = '/Users/pranaymishra/Desktop/sih1429/ommas_main/static/data/unsatisfactory_work_grade/nqm/rawnqm.csv'

In [13]:
import csv
from itertools import islice

input_file_path = path
output_file_path = '/Users/pranaymishra/Desktop/sih1429/ommas_main/static/data/unsatisfactory_work_grade/nqm/prorawnqm.csv'

try:
    # Read the CSV file and skip the first two rows
    with open(input_file_path, 'r', newline='') as infile, open(output_file_path, 'w', newline='') as outfile:
        reader = csv.reader(infile)
        writer = csv.writer(outfile)

        # Skip the first two rows
        rows_to_skip = 2
        reader = islice(reader, rows_to_skip, None)

        # Write the remaining rows to the output file
        for row in reader:
            writer.writerow(row)

    print(f"First two rows deleted from {input_file_path}. Result saved to {output_file_path}")

except Exception as e:
    print(f"An error occurred: {e}")

First two rows deleted from /Users/pranaymishra/Desktop/sih1429/ommas_main/static/data/unsatisfactory_work_grade/nqm/rawnqm.csv. Result saved to /Users/pranaymishra/Desktop/sih1429/ommas_main/static/data/unsatisfactory_work_grade/nqm/prorawnqm.csv

In [14]:
df = pd.read_csv(output_file_path)

In [15]:
df

,Textbox18,Textbox33,LOCATION_NAME,IMS_YEAR,Textbox8,TOTAL_PROPOSALS,LEN_COMPLETED,EXP_AMT,Textbox4,Textbox14,...,Textbox43,Textbox9,Textbox24,Textbox25,Textbox26,Textbox5,Textbox15,Textbox20,Textbox38,Textbox44
0,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,0,0,0.00%,0,0.00%,0,...,0.00%,"1,778",21,1.18%,68,3.82%,80,4.50%,10,0.56%
1,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,21,0,0.00%,2,9.52%,0,...,0.00%,"3,582",82,2.29%,170,4.75%,134,3.74%,57,1.59%
2,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,66,0,0.00%,0,0.00%,5,...,0.00%,"1,778",21,1.18%,68,3.82%,80,4.50%,10,0.56%
3,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,94,0,0.00%,5,5.32%,5,...,4.26%,"3,582",82,2.29%,170,4.75%,134,3.74%,57,1.59%
4,State,3,Arunachal Pradesh,Unsatisfactory works grading during 2...,40,2,5.00%,2,5.00%,3,...,5.00%,"1,778",21,1.18%,68,3.82%,80,4.50%,10,0.56%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,State,29,Uttar Pradesh,Unsatisfactory works grading during 2...,363,5,1.38%,32,8.82%,7,...,0.00%,"3,582",82,2.29%,170,4.75%,134,3.74%,57,1.59%
58,State,30,Uttarakhand,Unsatisfactory works grading during 2...,73,0,0.00%,4,5.48%,0,...,1.37%,"1,778",21,1.18%,68,3.82%,80,4.50%,10,0.56%
59,State,30,Uttarakhand,Unsatisfactory works grading during 2...,132,9,6.82%,4,3.03%,14,...,5.30%,"3,582",82,2.29%,170,4.75%,134,3.74%,57,1.59%
60,State,31,West Bengal,Unsatisfactory works grading during 2...,43,3,6.98%,0,0.00%,10,...,0.00%,"1,778",21,1.18%,68,3.82%,80,4.50%,10,0.56%
61,State,31,West Bengal,Unsatisfactory works grading during 2...,51,2,3.92%,2,3.92%,8,...,0.00%,"3,582",82,2.29%,170,4.75%,134,3.74%,57,1.59%

In [16]:
columns_to_keep_indices = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9,10,11,12]

# Select the columns to keep using iloc
df = df.iloc[:, columns_to_keep_indices]

In [17]:
df

,Textbox18,Textbox33,LOCATION_NAME,IMS_YEAR,Textbox8,TOTAL_PROPOSALS,LEN_COMPLETED,EXP_AMT,Textbox4,Textbox14,Textbox19,Textbox37,Textbox43
0,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,0,0,0.00%,0,0.00%,0,0.00%,0,0.00%
1,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,21,0,0.00%,2,9.52%,0,0.00%,0,0.00%
2,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,66,0,0.00%,0,0.00%,5,7.58%,0,0.00%
3,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,94,0,0.00%,5,5.32%,5,5.32%,4,4.26%
4,State,3,Arunachal Pradesh,Unsatisfactory works grading during 2...,40,2,5.00%,2,5.00%,3,7.50%,2,5.00%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,State,29,Uttar Pradesh,Unsatisfactory works grading during 2...,363,5,1.38%,32,8.82%,7,1.93%,0,0.00%
58,State,30,Uttarakhand,Unsatisfactory works grading during 2...,73,0,0.00%,4,5.48%,0,0.00%,1,1.37%
59,State,30,Uttarakhand,Unsatisfactory works grading during 2...,132,9,6.82%,4,3.03%,14,10.61%,7,5.30%
60,State,31,West Bengal,Unsatisfactory works grading during 2...,43,3,6.98%,0,0.00%,10,23.26%,0,0.00%
61,State,31,West Bengal,Unsatisfactory works grading during 2...,51,2,3.92%,2,3.92%,8,15.69%,0,0.00%

In [18]:
import pandas as pd

# Assuming df is your DataFrame with the selected columns
columns_to_keep = ['Textbox18', 'Textbox33', 'LOCATION_NAME', 'IMS_YEAR', 'Textbox8', 'TOTAL_PROPOSALS',
                   'LEN_COMPLETED', 'EXP_AMT', 'Textbox4', 'Textbox14', 'Textbox19', 'Textbox37', 'Textbox43']

# Select the columns to keep
df = df[columns_to_keep]

# Rename the columns with relevant names
new_column_names = {
    'Textbox18': 'State',
    'Textbox33': 'IMS_Year_Category',
    'LOCATION_NAME': 'Location',
    'IMS_YEAR': 'Description',
    'Textbox8': 'Total_Inspection_Completed_Works',
    'TOTAL_PROPOSALS': 'Completed_Works_U%',
    'LEN_COMPLETED': 'Ongoing_Works',
    'EXP_AMT': 'Ongoing_U%',
    'Textbox4': 'Maintenance_Works',
    'Textbox14': 'Maintenance_U%',
    'Textbox19': 'Bridge_Works',
    'Textbox37': 'Bridge_U%',
    'Textbox43': 'Total_Inspection'
}

df.rename(columns=new_column_names, inplace=True)

# Display the modified DataFrame

In [19]:
df

,State,IMS_Year_Category,Location,Description,Total_Inspection_Completed_Works,Completed_Works_U%,Ongoing_Works,Ongoing_U%,Maintenance_Works,Maintenance_U%,Bridge_Works,Bridge_U%,Total_Inspection
0,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,0,0,0.00%,0,0.00%,0,0.00%,0,0.00%
1,State,1,Andaman And Nicobar,Unsatisfactory works grading during 2...,21,0,0.00%,2,9.52%,0,0.00%,0,0.00%
2,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,66,0,0.00%,0,0.00%,5,7.58%,0,0.00%
3,State,2,Andhra Pradesh,Unsatisfactory works grading during 2...,94,0,0.00%,5,5.32%,5,5.32%,4,4.26%
4,State,3,Arunachal Pradesh,Unsatisfactory works grading during 2...,40,2,5.00%,2,5.00%,3,7.50%,2,5.00%
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,State,29,Uttar Pradesh,Unsatisfactory works grading during 2...,363,5,1.38%,32,8.82%,7,1.93%,0,0.00%
58,State,30,Uttarakhand,Unsatisfactory works grading during 2...,73,0,0.00%,4,5.48%,0,0.00%,1,1.37%
59,State,30,Uttarakhand,Unsatisfactory works grading during 2...,132,9,6.82%,4,3.03%,14,10.61%,7,5.30%
60,State,31,West Bengal,Unsatisfactory works grading during 2...,43,3,6.98%,0,0.00%,10,23.26%,0,0.00%
61,State,31,West Bengal,Unsatisfactory works grading during 2...,51,2,3.92%,2,3.92%,8,15.69%,0,0.00%

In [20]:
df = df.drop(['State'], axis=1)

In [21]:
df.to_csv(output_file_path, index=False)